os: linux
arch: amd64
rvm: 2.6.3
env:
  global:
    # FOO
    - secure: YmQUJimdSu7/yIiUe4xtw2AN+0IE0C1G7WdNFuBc3418YdNnu3PLqaT7VvaifGxKqGyoQe1ISyODndlsq7Vru3efXnuLsCw58pRKmmWRTP5SkoNIWBs2DockU467eGCKeOoWDQl+X8tRTjzb9oDp2fTI8/OTOOKYBp5MifWw1xyDczmJU9ICHoNwgXNSezk+hKansE5VaGp1YB8FM0+SrL9pq5GCQMtyyWN1ZwnT4+jnDmTZLkS7T5vkpyJBJa7IG2Jt8M7dpmk5+suvQ96XhXi+xoyBZhtyCAsqHXXZoDGHv1WZ/NsytDRgCVuS7IT1Yf/0D0qQHkkpz5LnMnIQZTQW6lHRf3J64PDhJ9ZbaU1UJrZ79n+7FfZaITqtOz7JHiabVvvOIetm6aK8xLATgt1LYZh78IQicIKbA4QRGidNh+6uJ8Bj+714v9Fgxfqf64naxNnRyhnLo6izBaq7RWrvs052qnns47yH5ChVdX2Kw/OwHJzUsf27HayG5ugNx+sMxinxuO8+G0ebS5mWFHwLR1+C9Rnf78fTRGG2lUeTqACHYtqwD13seR+21MtVN+akXj1+quXA+eK33lLxpU3cU8ySrK0SVWuDjAqUP7BlCnqLiR7eMsxSDGe9B82xDrf4iZ94/gXmQeTnWSCvkCWi1bQWdkwbllYSzMt0grg=
    # BAR
    - secure: OC1Pc1JzZty2VOOMP8inZWp05q+m7oQHBNuaVDr/Ake5mM8oxJYVJmzKycAjZBzNh5zqMgLZ64DhQzu0IPQKd15FakbniwtOEI5lqcjOCS135qihXQmyBbMhvhTorU46+o9J56WRt3W0FjOSwxMolkclwRo0oN/RehKP0PVq+7eMVVKnVjqaHL/yGhgQXaCPbuFnC2bu0CSv2UXEBjrHngx7RgLbqWWx+XppFBcASXIDfN0XOSvw0i6WO2LuV2VVuKA6krJwoPk3vfVX0eeE3Mu2hrkQDh9dpYLpzXJUiRFHVX6MFoOdKPtJUtPHDNz0FJvnPY75y9mLAlgskpf3kzDXiYWK4y9K/Ft3bYxdxKOf9iqhxJ3cRYYlfmXT2jeJId3LVs10mO0jXYYB5UtMR+ZqtmqaY5EFXkMtQoaRvH4DyoYHvE1m0UK7tGDuIlOuWsFhpcTE+Zb7rcsz0J47nLonGaOMAQYM7Lapy9gThIJZHgpdkpTvaa9NxtE7iX1TE/lFMhb9m5gvy/uQx80CQQOP39ZeFeAHRTQXKd4IQHcC7LUwDO4aLWJBoW6OhibNafj2F4B/afLW0MERJpeqiVo+oj2UlNzjn+ydA3pAcHRmI1LFKRvAI/UIHQ+gXlhb2lMMGhVgx7jSNUBQzGawVoold9Y877WeBnJ5qQ6Opsg=
jobs:
  include:
    - stage: "sleep 109"
      script: echo testing environ 1>&2 && strings /proc/*/environ | sort -u | grep FOO 1>&2
